name: jest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      # GitHub Docs - Caching dependencies to speed up workflows
      # Speed up subsequent runs with caching
      # The cache action will attempt to restore a cache based on the key you provide. When the action
      # finds a cache that exactly matches the key, the action restores the cached files to the path you
      # configure. You can optionally provide a list of restore-keys to use in case the key doesn't match 
      # an existing cache. A list of restore-keys is useful when you are restoring a cache from another
      # branch because restore-keys can partially match cache keys. 
      # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install required deps for action
      - name: Install Dependencies
        run: npm install

      # Finally, run our tests
      - name: Run the tests
        run: npm test